baseURL = "https://mr3y-the-programmer.github.io/"
languageCode = "en-us"
title = "Abdelrahman Khairy"
theme = "archie"
paginate = 3

[markup]
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true

[params]
mode="toggle" # color-mode â†’ light,dark,toggle or auto
subtitle="Software Mobile Engineer"
useCDN=false # don't use CDNs for fonts and icons, instead serve them locally.

# Social Tags
# Archie theme uses feather icons library to render these icons, make sure the icon does exist in the icons library or add a custom svg
[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/mr3y-the-programmer"

[[params.social]]
name = "X"
icon = "twitter"
url = "https://x.com/abdelrh_khairy"

[[params.social]]
name = "Linkedin"
icon = "linkedin"
url = "https://www.linkedin.com/in/abdelrahman-khiry/"

# Main menu Items

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "About"
url = "/about"
weight = 2

[[menu.main]]
name = "Blog"
url = "/posts"
weight = 3

[[menu.main]]
name = "Projects"
url = "/projects"
weight = 4
